django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.views import UserProfileView, UserProfileEditView
from user import views as user_views

urlpatterns = [
    path('', include('jollywood.urls')),
    path('cpanel/', admin.site.urls),
    path('register/', user_views.register, name='user-register'),
    path('profile/', user_views.redirector, name='user-redirect-to-profile'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', extra_context={'title': 'Log In'}), name='user-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html', extra_context={'title': 'Log Out'}), name='user-logout'),
    path('<slug>/', UserProfileView.as_view(), name='user-profile'),
    path('<slug>/edit', UserProfileEditView.as_view(), name='user-profile-edit'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jollywood/urls.py
from . import views
from django.urls import path
from jollywood.models import Books

urlpatterns = [
    path('', views.home, name='jollywood-home'),
    path('bookslist/', views.book_list, name='jollywood-bookslist'),
    path('about/', views.about, name='jollywood-about'),
    path('books/<slug>/', views.Books.as_view(extra_context={'title': 'Books'}), name='jollywood-books'),
    path('contact/', views.contact, name='jollywood-contact'),
    path('english/', views.english, name='jollywood-english'),
    path('russian/', views.russian, name='jollywood-russian'),
    path('mathematics/', views.mathematics, name='jollywood-mathematics'),
    path('kids/', views.kids, name='jollywood-kids'),
    path('tests/', views.tests, name='jollywood-tests'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse
from django.utils import timezone

class UserProfile(User):
	levels = [
		('Beginner', 'Beginner'),
		('Elementary', 'Elementary'),
		('Pre-Intermediate', 'Pre-Intermediate'),
		('Intermediate', 'Intermediate'),
		('Upper-Intermediate', 'Upper-Intermediate'),
		('Advanced', 'Advanced'),
	]

	courses = [
		('English', 'English'),
		('Russian', 'Russian'),
		('Mathematics', 'Mathematics'),

	]

	titles = [
		('Teacher', 'Teacher'),
		('Student', 'Student'),
	]

	icons = [
		('fa-user', 'User'),
		('fa-user-graduate', 'Student'),
		('fa-user-ninja', 'Ninja'),
		('fa-user-tie', 'Tie'),
		('fa-user-md', 'Doctor'),
		('fa-user-astronaut', 'Astronaut'),
		('fa-user-secret', 'Spy'),
		('fa-user-injured', 'Injured'),
	]

	bio = models.TextField(blank=True, null=True)
	country = models.CharField(max_length = 100, blank=True, null=True)
	course = models.CharField(
		max_length = 20,
		choices=courses,
		default='English',
	)
	level = models.CharField(
		max_length = 20,
		choices=levels,
		default='Beginner',
	)
	title = models.CharField(
		max_length = 20,
		choices=titles,
		default='Student',
	)
	avatar = models.ImageField(default='avatars/default_avatar.jpg', upload_to='avatars')
	icon = models.CharField(
		max_length = 150,
		choices = icons,
		default = 'fa-user'
	)
	instagram = models.CharField(max_length = 100, blank=True, null=True)
	facebook = models.CharField(max_length = 100, blank=True, null=True)
	twitter = models.CharField(max_length = 100, blank=True, null=True)
	telegram = models.CharField(max_length = 100, blank=True, null=True)

	def is_student(self):
		return self.title == 'Student'


	def is_teacher(self):
		return self.title == 'Teacher'

	def get_absolute_url(self):
		return reverse('user-profile', kwargs={'slug': self.username})

	def __str__(self):
		return f'{self.username} Profile'

	def save(self, **kwargs):
		super().save()

		img = Image.open(self.avatar.path)

		if img.height != img.width:
			w = img.width
			h = img.height

			if h > w:
				a = h - w
				box = (a/2, a/2, w, w)
			else:
				a = w - h
				box = (a/2, a/2, h, h)

			img = img.crop(box)

			if img.height > 500 or img.width > 500:
				output_size = (500, 500)
				img.thumbnail(output_size)
				img.save(self.avatar.path)
			else:
				img.save(self.avatar.path)


class Status(models.Model):
	text = models.TextField(blank=True)
	img = models.ImageField(blank=True, null=True, upload_to='userstatuses')
	likes = models.PositiveIntegerField(default=0)
	time = models.DateTimeField(default=timezone.now)
	owner = models.ForeignKey('UserProfile', on_delete=models.CASCADE)

	class Meta:
		verbose_name = 'Status'
		verbose_name_plural = 'Statuses'
		ordering = ['-id']



	def __str__(self):
		return f'No {self.id} Status by {self.owner.username}'


	def save(self, **kwargs):
		super().save()

		img = Image.open(self.img.path)

		if img.height > 500 or img.width > 500:
			output_size = (500, 500)
			img.thumbnail(output_size)
			img.save(self.img.path)
		else:
			img.save(self.img.path)

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import UserProfile, Status


class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = UserProfile
		fields = ['username', 'first_name', 'last_name', 'password1', 'password2', 'email']


class StatusCreationForm(forms.ModelForm):

	class Meta:
		model = Status
		fields = ['text', 'img']


class BioUpdateForm(forms.ModelForm):

	class Meta:
		model = UserProfile
		fields = ['bio']


class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email']

user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import UserRegisterForm
from django.views.generic import UpdateView
from django.contrib.auth.models import User
from .models import UserProfile


def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Account for {username} was created successfully! You can now log in')
			return redirect('user-login')
	else:
		form = UserRegisterForm()
	return render(request, 'registration.html', {'form': form, 'title': 'Registration'})


@login_required
def redirector(request):
	return redirect('user-profile', request.user.username)


class UserProfileView(UpdateView):
	model = UserProfile
	fields = ['bio',]
	slug_field = 'username'
	template_name = 'profile.html'
	context_object_name = 'User'

class UserProfileEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = UserProfile
	fields = [
		'avatar',
		'first_name',
		'last_name',
		'email',
		'title',
		'course',
		'level',
		'country',
		'icon',
		'instagram',
		'facebook',
		'telegram',
		'twitter',
	]
	slug_field = 'username'
	template_name = 'profile_edit.html'
	context_object_name = 'User'

	def test_func(self):
		profile = self.get_object()

		if self.request.user.username == profile.username:
			return True
		return False

user/templates/login.html
{% extends 'rsc/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
		
	<div class="container mt-5 jumbotron">
		<div class="row">

			<div class="col-md-9">
					<div class="content-section">
					  {% if messages %}
					    {% for message in messages %}
					      <div class="alert alert-{{ message.tags }} text-center">
					        {{ message }}
					      </div>
					    {% endfor %}
					  {% endif %}
						<form method="POST">
							{% csrf_token %}
							<fieldset class="form-group">
								<legend class="border-bottom mb-3 text-primary display-4 text-center">Log In</legend>

								<div class="mx-5">
									{{ form|crispy }}
									<div class="form-group">
										<button type="submit" class="btn btn-outline bg-white btn-lg hvr-underline-from-center">Login</button>
									</div>
								</div>
							</fieldset>
						</form>

						<div class="border-top pt-3">
							<p class="text-muted">Need an account? <a href="{% url 'user-register' %}" class="ml-2 text-primary">Sign Up Now</a></p> 
						</div>

					</div>
			</div>

			{% include 'rsc/calendar.html' %}		
			
		</div>
	</div>

{% endblock content %}

user/templates/logout.html
{% extends 'rsc/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
		
	<div class="container mt-5 jumbotron">
		<div class="row">

			<div class="col-md-9">
					<div class="content-section">
						<h2 class="alert alert-info text-center">You have logged out!</h2>

						<div class="border-top pt-3">
							<p class="text-muted">Log in again? <a href="{% url 'user-login' %}" class="ml-2 text-primary">Log In</a></p> 
						</div>

					</div>
			</div>

			{% include 'rsc/calendar.html' %}		
			
		</div>
	</div>

{% endblock content %}

user/templates/profile.html
{% extends 'rsc/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
		
	<div class="container mt-5 ">
		<div class="row jumbotron">
			<div class="col-sm-3">
				<h4 class="card-title">{{ User.get_full_name }} <i class="fa {{ User.icon }} ml-1"></i></h4>
				<div class="card p-2">
					<img src="{{ User.avatar.url }}" class="img img-thumbnail rounded-circle card-img-top">
					<div class="card-body">
						{% if User.title == 'Teacher' %}
						<h5 class="card-title">{{ User.title }}</h5>
						<h6 class="card-title">Course: {{ User.course }}</h6>
						{% else %}
						<h5 class="card-title">{{ User.title }}</h5>
						<h6 class="card-text">Course: {{ User.course }} {{ User.level }}</h6>
						{% endif %}
					</div>
				</div>
				<br>
				<hr>
				<legend>Bio:</legend>
				<div class="card-body card">
					{% if User.bio %}
					<p class="card-text text-center">{{ User.bio }}</p>
					{% else %}
					<p class="card-text text-center alert alert-warning alert-dismissable">There is no biography for {{ User.first_name }}</p>
					{% endif %}

					{% if User.username == user.username %}
					<form method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						<div style="display: none" id="bio-change">
							{{ form|crispy }}
							<button class="btn border-success bg-white hvr-icon-bob text-success btn-sm form-group float-right" type="submit">Edit <i class="far fa-edit ml-1 hvr-icon"></i></button>
						</div>
					</form>
					<button class="btn border-primary text-primary bg-white hvr-icon-bob" id="bio-toggle">Update bio<i class="fa fa-pen-fancy hvr-icon ml-2"></i></button>
					{% endif %}

				</div>
			</div>

			<div class="col-sm-6">
				<!-- Here Should be all the charts and so on so on so on so on so on so on -->
			</div>

			<div class="col-sm-3">
				<div class="card p-2">
					<legend>Account Info:</legend>
					<p class="card-text text-muted"><i class="fas fa-at mr-2"></i>Username: {{ User.username }}</p>
					<p class="card-text text-muted"><i class="fa fa-map-marker-alt mr-2"></i>From: {{ User.country }}</p>
					<p class="card-text text-muted"><i class="far fa-clock mr-2"></i>Last login: {{ User.last_login|date:"M d, H:i" }}</p>
					<p class="card-text text-muted"><i class="fas fa-envelope mr-2"></i>Email: {{ User.email }}</p>
					<p class="card-text text-muted"><i class="fas fa-history mr-2"></i>Joined on: {{ User.date_joined|date:"M d, Y" }}</p>
					<br>
				</div>
				<hr>
				<div class="card p-2">
					<legend>Social Accounts:</legend>
					{% if User.instagram %}
					<p class="card-text text-muted"><i class="fab fa-lg fa-instagram mr-2"></i>Instagram: {{ User.instagram }}</p>
					{% endif %}
					{% if User.facebook %}
					<p class="card-text text-muted"><i class="fab fa-lg fa-facebook mr-2"></i>Facebook: {{ User.facebook }}</p>
					{% endif %}
					{% if User.twitter %}
					<p class="card-text text-muted"><i class="fab fa-lg fa-twitter mr-2"></i>Twitter: {{ User.twitter }}</p>
					{% endif %}
					{% if User.telegram %}
					<p class="card-text text-muted"><i class="fab fa-lg fa-telegram-plane mr-2"></i>Telegram: {{ User.telegram }}</p>
					{% endif %}
					{% if not User.telegram and not User.twitter and not User.facebook and not User.instagram %}
					<p>There are no accounts added!</p>
					{% endif %}
				</div>
				<hr>
				{% if User.username == user.username %}
				<div class="card p-2">
					<a href="{% url 'user-profile-edit' User.username %}" class="btn border-warning bg-white hvr-icon-bob text-warning">Edit Profile Info<i class="fa far fa-edit hvr-icon ml-2"></i></a>
				</div>
				{% endif %}
			</div>
		</div>
		<div class="row jumbotron">
			{% if User.status_set.all %}
				{% for status in User.status_set.all %}
					<div class="card p-2 mb-2">
						<img src="{{ status.img.url }}" class="card-img-top img img-thumbnail">
						<div class="card-body">
							<h5 class="card-title">{{ status.text }}</h5>
							<small class="card-text float-right text-muted">{{ status.time }}</small>
						</div>
					</div>
					<hr>
				{% endfor %}
			{% else %}
			<h3 class="alert alert-warning alert-dismissable mx-auto">There are no statuses for {{ User.first_name }}</h3>
			{% endif %}
		</div>
	</div>
	
	<script>
	
		$(function() {
			
			$('#bio-toggle').on('click', function(){
				$('#bio-change').toggle(300)

				if($(this).html() == 'Update bio<i class="fa fa-pen-fancy hvr-icon ml-2"></i>'){
					$(this).html('Cancel<i class="fa fa-times-circle hvr-icon ml-2"></i>')
				} else {
					$(this).html('Update bio<i class="fa fa-pen-fancy hvr-icon ml-2"></i>')
				}

			});

		});

	</script>

{% endblock content %}

user/templates/profile_edit.html
{% extends 'rsc/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
		
	<div class="container mt-5 jumbotron">
		<div class="row">

			<div class="col-md-9">
					<div class="content-section">

						<form method="POST" enctype="multipart/form-data">
							{% csrf_token %}
							<fieldset class="form-group">
								<legend class="border-bottom mb-3 display-4 text-center">Update Profile Info</legend>							
								<div class="mx-5">
									{{ form|crispy }}
									<div class="form-group">
										<button type="submit" class="btn btn-outline text-primary bg-white hvr-underline-from-center">Save Changes</button>
									</div>
								</div>
							</fieldset>
						</form>
					</div>
			</div>

			{% include 'rsc/calendar.html' %}		
			
		</div>
	</div>

{% endblock content %}

user/templates/registration.html
{% extends 'rsc/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
		
	<div class="container mt-5 jumbotron">
		<div class="row">

			<div class="col-md-9">
					<div class="content-section">

						<form method="POST">
							{% csrf_token %}
							<fieldset class="form-group">
								<legend class="border-bottom mb-3 display-4 text-center">Join Today</legend>							
								<div class="mx-5">
									{{ form|crispy }}
									<div class="form-group">
										<button type="submit" class="btn btn-outline text-primary bg-white hvr-underline-from-center">Sign up</button>
									</div>
								</div>
							</fieldset>
						</form>

						<div class="border-top pt-3">
							<p class="text-muted">Already have an account? <a href="{% url 'user-login' %}" class="ml-2 text-primary">Sign In</a></p> 
						</div>

					</div>
			</div>

			{% include 'rsc/calendar.html' %}		
			
		</div>
	</div>

{% endblock content %}

user/templates/test.html
{% extends 'rsc/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
		
	<div class="container mt-5 jumbotron">
		<div class="row">

			<div class="col-md-9">
				
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form|crispy }}
					<button class="btn btn-outline-success btn-sm form-group float-right" type="submit">Save <i class="far fa-save ml-1"></i></button>
				</form>

			</div>

			{% include 'rsc/calendar.html' %}		
			
		</div>
	</div>

{% endblock content %}